version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Flask app port
    volumes:
      - ./application:/app/application  # Mount application directory
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development